### ISSUE TITLE
能否支持抽屉自动隐藏

### ISSUE THREAD

**Issue by slackzh** [Leaqi/SwipeDrawer#10]
我现在做法不是很优雅

1. 在 setOnDrawerSwitch -> onOpen 里开启定时器，超时则关闭抽屉
2. leftLayout 用自定义的 LinearLayout 类，在 onDispatchTouch 事件中增加一个回调，遇到 ACTION_UP 或者 ACTION_CANCEL 则复位定时器

**Comment by Leaqi** [comment]
> 我现在做法不是很优雅
> 
> 1. 在 setOnDrawerSwitch -> onOpen 里开启定时器，超时则关闭抽屉
> 2. leftLayout 用自定义的 LinearLayout 类，在 onDispatchTouch 事件中增加一个回调，遇到 ACTION_UP 或者 ACTION_CANCEL 则复位定时器

相关代码发来看看

**Comment by slackzh** [comment]
```java
// 抽屉打开时，开始定时器
mBinding.rootDrawer.setOnDrawerSwitch(new OnDrawerSwitch() {
        @Override
        public void onOpen(SwipeDrawer view) {
            Log.d(TAG, "rootDrawer onOpen");
            ......
            mHandler.removeCallbacks(mRunableCloseDrawer);
            mHandler.postDelayed(mRunableCloseDrawer, mDrawerTimeout);
        }

        @Override
        public void onClose(SwipeDrawer view) {
            Log.d(TAG, "rootDrawer onClose");
            .......
            mHandler.removeCallbacks(mRunableCloseDrawer);
        }
});
```


```java
// SwiperDrawer 的子 View 用自定义的 LinearLayout，回调 dispatchTouchEvent
DrawerBox leftBox = (DrawerBox) mBinding.rootDrawer.getLeftView();
DrawerBox rightBox = (DrawerBox) mBinding.rootDrawer.getRightView();
DrawerBox topBox = (DrawerBox) mBinding.rootDrawer.getTopView();
if(leftBox != null)
        leftBox.setOnDispatchTouchListener(mDrawerTouchListener);
if(rightBox != null)
        rightBox.setOnDispatchTouchListener(mDrawerTouchListener);
if(topBox != null)
        topBox.setOnDispatchTouchListener(mDrawerTouchListener);
```

```java
//  监听抽屉内部的 Touch 事件，包括其子 View
// 有触摸时重置计时器
private final DrawerBox.OnDispatchTouchListener mDrawerTouchListener = new DrawerBox.OnDispatchTouchListener() {
    @Override
    public void onAction(int action) {
        Log.d(TAG, "rootDrawer touch: " + action);
        switch (action) {
            case MotionEvent.ACTION_UP:
            case MotionEvent.ACTION_CANCEL:
                mHandler.removeCallbacks(mRunableCloseDrawer);
                mHandler.postDelayed(mRunableCloseDrawer, mDrawerTimeout);
            break;
        }
    }
};
```

**Comment by Leaqi** [comment]
> ```java
> // 抽屉打开时，开始定时器
> mBinding.rootDrawer.setOnDrawerSwitch(new OnDrawerSwitch() {
>         @Override
>         public void onOpen(SwipeDrawer view) {
>             Log.d(TAG, "rootDrawer onOpen");
>             ......
>             mHandler.removeCallbacks(mRunableCloseDrawer);
>             mHandler.postDelayed(mRunableCloseDrawer, mDrawerTimeout);
>         }
> 
>         @Override
>         public void onClose(SwipeDrawer view) {
>             Log.d(TAG, "rootDrawer onClose");
>             .......
>             mHandler.removeCallbacks(mRunableCloseDrawer);
>         }
> });
> ```
> 
> ```java
> // SwiperDrawer 的子 View 用自定义的 LinearLayout，回调 dispatchTouchEvent
> DrawerBox leftBox = (DrawerBox) mBinding.rootDrawer.getLeftView();
> DrawerBox rightBox = (DrawerBox) mBinding.rootDrawer.getRightView();
> DrawerBox topBox = (DrawerBox) mBinding.rootDrawer.getTopView();
> if(leftBox != null)
>         leftBox.setOnDispatchTouchListener(mDrawerTouchListener);
> if(rightBox != null)
>         rightBox.setOnDispatchTouchListener(mDrawerTouchListener);
> if(topBox != null)
>         topBox.setOnDispatchTouchListener(mDrawerTouchListener);
> ```
> 
> ```java
> //  监听抽屉内部的 Touch 事件，包括其子 View
> // 有触摸时重置计时器
> private final DrawerBox.OnDispatchTouchListener mDrawerTouchListener = new DrawerBox.OnDispatchTouchListener() {
>     @Override
>     public void onAction(int action) {
>         Log.d(TAG, "rootDrawer touch: " + action);
>         switch (action) {
>             case MotionEvent.ACTION_UP:
>             case MotionEvent.ACTION_CANCEL:
>                 mHandler.removeCallbacks(mRunableCloseDrawer);
>                 mHandler.postDelayed(mRunableCloseDrawer, mDrawerTimeout);
>             break;
>         }
>     }
> };
> ```

这个看要在什么场景下使用，如果非得是超时关闭的话，也只能用定时器了。

**Comment by slackzh** [comment]
比方说一些公用的触屏设备上，希望用户操作完之后恢复原样，方便下一个用户操作
