### ISSUE TITLE
强制手机横屏，view显示异常

### ISSUE THREAD

**Issue by jy7758258** [Leaqi/SwipeDrawer#3]
手机在竖屏情况下没有问题，但是强制设置手机为横屏情况，这个view就只会显示一半了（可能跟手机的分辨率有关系）

**Comment by jy7758258** [comment]
不是在Scrollview中，我在SwipeDrawer中加入了一个right和bottom的layout，当竖屏时open bottom的布局，横屏时open right布局，竖屏情况没有问题，横屏时的背景蒙层只能显示到屏幕的一半（没有挨着right 布局，中间间隔的是main里面的布局）

`<SwipeDrawer
        android:layout_width="match_parent"
        android:id="@+id/mainDrawer"
        app:mode="cover"
        app:mask="general"
        app:maskClose="true"
        app:maskColor="@color/black_80"
        app:mainOpen="click"
        app:rightLayout="@+id/rlRight"
        app:rightDragOpen="false"
        app:bottomDragOpen="false"
        app:bottomLayout="@+id/rlBottom"
        app:bottomMode="cover"
        app:rightMode="cover"
        android:layout_height="match_parent">
        <com.ruffian.library.widget.RLinearLayout
            android:id="@+id/rlRight"
            android:layout_width="300dp"
            app:corner_radius_top_left="@dimen/dp_12"
            app:corner_radius_bottom_left="@dimen/dp_12"
            app:background_normal="@color/white"
            android:layout_height="match_parent">
        </com.ruffian.library.widget.RLinearLayout>
        <com.ruffian.library.widget.RLinearLayout
            android:id="@+id/rlBottom"
            android:layout_width="match_parent"
            app:background_normal="@color/white"
            app:corner_radius_top_left="@dimen/dp_12"
            app:corner_radius_top_right="@dimen/dp_12"
            android:layout_height="320dp">
        </com.ruffian.library.widget.RLinearLayout>
</SwipeDrawer>`

**Comment by Leaqi** [comment]
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <cn.leaqi.drawer.SwipeDrawer
        android:id="@+id/mainDrawer"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:bottomLayout="@+id/rlBottom"
        app:bottomMode="cover"
        app:mainOpen="click"
        app:mask="general"
        app:maskClose="true"
        app:maskColor="#80000000"
        app:mode="cover"
        app:rightLayout="@+id/rlRight"
        app:rightMode="cover">

        <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@color/colorPrimary" />

        <com.ruffian.library.widget.RLinearLayout
            android:id="@+id/rlRight"
            android:layout_width="300dp"
            android:layout_height="match_parent"
            app:background_normal="#ffffff"
            app:corner_radius_bottom_left="12dp"
            app:corner_radius_top_left="12dp" />

        <com.ruffian.library.widget.RLinearLayout
            android:id="@+id/rlBottom"
            android:layout_width="match_parent"
            android:layout_height="320dp"
            app:background_normal="#ffffff"
            app:corner_radius_top_left="12dp"
            app:corner_radius_top_right="12dp" />
    </cn.leaqi.drawer.SwipeDrawer>

</RelativeLayout>

这是我测试的结果，没发现什么异常啊，你发下完整代码看看。

**图：**
[https://p.ssl.qhimg.com/t01da3a2f07e3745e06.png](https://p.ssl.qhimg.com/t01da3a2f07e3745e06.png)
[https://p.ssl.qhimg.com/t01e8263b7033160a66.png](https://p.ssl.qhimg.com/t01e8263b7033160a66.png)
[https://p.ssl.qhimg.com/t01b2ef924b44779fd3.png](https://p.ssl.qhimg.com/t01b2ef924b44779fd3.png)
[https://p.ssl.qhimg.com/t01da41946facd4be01.png](https://p.ssl.qhimg.com/t01da41946facd4be01.png)

**Comment by Leaqi** [comment]
３３５９９４６７７
