### ISSUE TITLE
设置把手handle

### ISSUE THREAD

**Issue by HRlijie** [Leaqi/SwipeDrawer#5]
您好！请问怎么设置把手handle,用于拖动上下拉之类的

**Comment by Leaqi** [comment]
具体是要做成什么效果？

**Comment by HRlijie** [comment]
![image](https://user-images.githubusercontent.com/51016974/223373483-a81b23c4-73c3-4d02-9e37-8a78bfe697b8.png)
类似高德地图主页面，有个底部导航，有上拉抽屉效果

**Comment by Leaqi** [comment]
效果：
![image](https://p.ssl.qhimg.com/t019011351bda476d4b.gif)

布局：
`
<cn.leaqi.drawer.SwipeDrawer
    ...
    android:id="@+id/mainDrawer"
    app:mode="cover"
    app:dragRange="100dp" //边缘滑动设置初始高度
    app:bottomLayout="@+id/bottomLayout">
	//隐藏的抽屉布局
    <RelativeLayout
        android:id="@+id/bottomLayout"
        android:layout_width="match_parent"
        android:layout_height="300dp" />
    <RelativeLayout style="@style/MainMatch">
		//主布局
        <RelativeLayout 
		...
		android:background="#eeeeee" 
		android:layout_alignParentTop="true">
            ...
        </RelativeLayout>
		//布局初始高度100dp，根据打开进度动态设置高度
        <LinearLayout
            android:id="@+id/btnList"
            android:layout_width="match_parent"
            android:layout_height="100dp"
            android:background="#8BC34A"
            android:orientation="vertical"
            android:layout_alignParentBottom="true">
            <TextView
                ...
                android:text="111" />
            <TextView
                ...
                android:text="222" />
            <TextView
                ...
                android:text="333" />
        </LinearLayout>
    </RelativeLayout>
</cn.leaqi.drawer.SwipeDrawer>
`

代码：
`        final SwipeDrawer mainDrawer = findViewById(R.id.mainDrawer);
        final View btnList = findViewById(R.id.btnList);
        mainDrawer.setOnDrawerState(new OnDrawerState() {
            @Override
            public void onStart(int type) {}
            @Override
            public void onMove(int type, float progress) {
                //根据进度动态设置布局高度
                ViewGroup.LayoutParams params = btnList.getLayoutParams();
                params.height = Common.dipToPx(getBaseContext(), 100 + 200 * progress);
                btnList.setLayoutParams(params);
            }
            @Override
            public void onOpen(int type) {}
            @Override
            public void onClose(int type) {}
            @Override
            public void onCancel(int type) {}
        });`


目前只能用这种方法实现，后续升级会考虑加进去

**Comment by HRlijie** [comment]
我试试，感谢大佬

**Comment by Leaqi** [comment]
版本 1.5 中已加入该功能 [bottomOffset](https://leaqi.github.io/SwipeDrawer/code.html#bottomOffset)
