### ISSUE TITLE
手势处理上有点问题，drawer 通过手势滑动打开到一部分后，不能通过手势关闭

### ISSUE THREAD

**Issue by appdev** [Leaqi/SwipeDrawer#6]
demo上都能复现，在底部弹出这个页面最明显，手势向上滑动 打开 drawer 到屏幕 1/3 的位置，这时候，手势向下滑动，意图关闭 drawer ，但是松手后 drawer 还是会打开。

https://github.com/Leaqi/SwipeDrawer/assets/9107717/a3adc9bf-a3af-4f33-b8df-aa5752cb962a

**Comment by Leaqi** [comment]
默认是20%
关闭的情况下，滑动距离只要大于20%都会打开。
打开的情况下，滑动距离只要大于20%都会关闭。

**Comment by Leaqi** [comment]
参考这个参数调整距离 [shrinkRange](https://leaqi.github.io/SwipeDrawer/code.html#shrinkRange)

**Comment by appdev** [comment]
> 参考这个参数调整距离 [shrinkRange](https://leaqi.github.io/SwipeDrawer/code.html#shrinkRange)

不是这个意思，shrinkRange 设置滑动距离后，比如：

向上滑动 100dp 允许打开 drawer 。这时候手指向上滑动超过100dp，但是手指不离开屏幕，向下滑动，这个距离已经小于100dp了，但是还是会打开 drawer。你可以看视频中的操作

**Comment by appdev** [comment]
我感觉应该是判断逻辑中，判断达到打开的条件后就没有继续处理后面的逻辑了；

**Comment by appdev** [comment]
> 我感觉应该是判断逻辑中，判断达到打开的条件后就没有继续处理后面的逻辑了；

我觉得如果检测到向下滑动的手势，就应该执行关闭drawer 的动画，比较应该符合用户的操作预期，参考系统的 ViewPager的操作。

**Comment by Leaqi** [comment]
ViewPager也不是你说的这种哦，包括一些大厂的软件，都没有你说的这种操作，都是到达指定距离才会打开、关闭。
ViewPager设置的大概是超过70% 才会打开。 把shrinkRange设置1.5就跟ViewPager就差不多了

**Comment by appdev** [comment]
> ViewPager也不是你说的这种哦，包括一些大厂的软件，都没有你说的这种操作，都是到达指定距离才会打开、关闭。 ViewPager设置的大概是超过70% 才会打开。 把shrinkRange设置1.5就跟ViewPager就差不多了

我说的不是打开距离问题。比如 demo 中的 底部弹出 这个页面，什么代码都不改，向上滑动漏出一半的 bottmlayout 。手指不离开屏幕。这时候向下滑动，应该关闭 drawer 比较好。

ViewPager 达到打开的距离后，向下滑动，就会关闭

在这个状态的时候。已经向下滑动了，但是还是会打开 drawer 
![image](https://github.com/Leaqi/SwipeDrawer/assets/9107717/627a14d9-9b3e-4e89-b343-b13625f27a52)

**Comment by Leaqi** [comment]
因为 demo 的这个页面shrinkRange设置的10，基本上只要滑动了  就会打开、shrinkRange这个参数可以适当调整下

这是shrinkRange的测试页
[![image](https://p.ssl.qhimg.com/t016c1ed797182a5c8d.gif)](https://p.ssl.qhimg.com/t016c1ed797182a5c8d.gif)

**Comment by Leaqi** [comment]
ViewPager2确实是你说的那样，SwipeDrawer暂时没有，后续版本可能考虑加进去。

**Comment by appdev** [comment]
稍微修改了一下，实现了这个效果：
- 在 onTouchEvent 的 ACTION_MOVE 中 增加一个判断 `progress < lastProgress` 
- 在 ACTION_UP 中判断最后最要是否是要取消打开动作
- 调用 `forceClose`关闭drawer

**Comment by Leaqi** [comment]
版本 1.6 中已加入该功能 [turnCancel](https://leaqi.github.io/SwipeDrawer/code.html#turnCancel)
