### ISSUE TITLE
设置把手问题

### ISSUE THREAD

**Issue by zy7576** [Leaqi/SwipeDrawer#8]
你好，我通过1.5版本新加入的app:bottomOffset="50dp"功能设置拖曳把手，一切如预期效果。
但是发现一个问题，就是一个页面如果有多个方向的抽屉，那么在拖曳其他方向时，有把手方向上的抽屉会带着把手一起完全隐藏，就意味着app:bottomOffset="50dp"属性效果失效了，然而点击遮挡层关闭时，是会把把手露出在主页面的。请教请教，谢谢！！！

**Comment by Leaqi** [comment]
代码发出来看看
